package com.su.daar.helper;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Formatter;
import java.util.logging.Handler;
import java.util.logging.LogRecord;


class CustomFormatter extends Formatter {
    // Create a DateFormat to format the logger timestamp.

    public String format(LogRecord record) {
        if(record.getMessage().indexOf("msg:")==0){
            // the custom created info/debug messages are preceded by the substring "msg:"
            // we filter the messages according to this prefix
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss.SSS");

            StringBuilder builder = new StringBuilder(1000);
            builder.append(df.format(new Date(record.getMillis()))).append(" - ");
            builder.append("[").append(record.getSourceClassName()).append(".");
            builder.append(record.getSourceMethodName()).append("] - ");
            builder.append("[").append(record.getLevel()).append("] - ");
            builder.append(formatMessage(record));
            builder.append("\n");

            return builder.toString();

        }else{

            return null;  // we are only interested in the customly created debug/info messages written by the developer, not these generated by the RE 
        
        }

    }

    public String getHead(Handler h) {
        return super.getHead(h);
    }

    public String getTail(Handler h) {
        return super.getTail(h);
    }
}